spring:
  application:
    name: TicketBooking-IndianRailway
  datasource:
    url: jdbc:mysql://localhost:3306/ticketbookingir?createDatabaseIfNotExist=true
    username: root
    password: Reddy@2001
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9098


